### ISSUE TITLE
Inconsistent weather icon display when set to Left

### ISSUE THREAD

**Issue by nhubaotruong** [somepaulo/GNOME-Shell-extension-Weather-or-Not#7] opened 2023-11-07 07:01 UTC
## Distro Name & Version
Fedora silverblue 39

## GNOME Shell Version
45

## Other Installed Extensions
No extension that conflict with this

## Expected Behavior
Correct weather icon location in the left (like in screenshot)
![image](https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/assets/28810481/4ac1a333-282f-4a28-89e7-51ce4be4c2d6)

## Current Behavior
![image](https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/assets/28810481/503cfc77-f8b8-4ce9-9ba3-0e5be0b433f6)

## Detailed Description
How to replicate:
- Enable extension, it will work as expected
- Lock the screen
- Login again
- Extension trigger weather update
- The weather icon is now in the wrong location

It appears to have inserted an extra element at 0 index
![image](https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/assets/28810481/739b5b58-403e-47ac-bba0-4ba3f04f3ffb)

**Comment by nhubaotruong** [comment] 2023-11-17 06:50
@somepaulo Hi, can you please take a look ?

**Comment by somepaulo** [comment] 2023-11-17 15:18
I can confirm this.
Seems to be either an issue with the method of adding the indicator not playing well with how the left box is recreated upon unlock or a timing problem.
Looking into this. Any help or suggestions welcome, as usual.

**Comment by somepaulo** [comment] 2023-11-17 16:41
The `Unite` extension suffers from the same bug. Something must've changed in the way GS buids the left panel box.  
For us it's fixed in 7975ac4.

Now, the weather indicator will always be the last one in the left box (the first one from the right edge of the left box), which might not work nice with extensions that bring the app menu/title back to the panel, since those would typically sit to the left of the weather indicator.  
I'll further research ways of waiting for the panel boxes to load, figuring out their contents, and only then inserting the indicator at the desired position, if possible. But later.

**Closed as completed by somepaulo** 2023-11-17 16:41 UTC
Labels: bug
